spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: endereco
          uri: lb://ENDERECO
          predicates:
            - Path=/end/**
        - id: cliente
          uri: lb://CLIENTE
          predicates:
            - Path=/cli/**
server:
  port: ${PORTA:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA}eureka
